services:
  jellyfin-auto-playlists:
    #build: .
    image: ghcr.io/sjorswijsman/jellyfin-auto-playlists:latest
    container_name: jellyfin-auto-playlists
    environment:
      - CRONTAB=0 0 * * *
      - TZ=America/New_York
      - JELLYFIN_SERVER_URL=https://www.jellyfin.example.com
      - JELLYFIN_API_KEY=1a1111aa1a1a1aaaa11a11aa111aaa11
      - JELLYFIN_USER_ID=2b2222bb2b2b2bbbb22b22bb222bbb22
    volumes:
      - ${CONFIG_DIR}/jellyfin-auto-playlists/config:/app/config
    restart: unless-stopped
